<div class="page-header"><h1>Panel de administración</h1><p>Gestiona el catálogo, las solicitudes y la disponibilidad de las máquinas.</p></div>
<?php if ($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?>
<?php if ($error): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?>

<section class="admin-section"><div class="admin-section-header"><h2>Solicitudes <span class="admin-count"><?= count($solicitudes) ?></span></h2></div><div class="admin-table-wrap"><table class="tabla-extras admin-table"><thead><tr><th>Cliente</th><th>Máquina</th><th>Fechas</th><th>Estado</th></tr></thead><tbody>
<?php if (!$solicitudes): ?><tr><td colspan="4" class="empty-state">Todavía no hay solicitudes.</td></tr><?php endif; ?>
<?php foreach ($solicitudes as $s): ?><tr><td><?= e($s['nombre_cliente']) ?><br><small><?= e($s['email_cliente']) ?><br><?= e($s['telefono_cliente']) ?></small></td><td><?= e($s['maquina_nombre']) ?></td><td><?= e($s['fecha_inicio']) ?> → <?= e($s['fecha_fin']) ?></td><td><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="estado"><input type="hidden" name="id" value="<?= $s['id'] ?>"><select name="estado" class="form-control"><option <?= $s['estado'] === 'Pendiente' ? 'selected' : '' ?>>Pendiente</option><option <?= $s['estado'] === 'Aprobada' ? 'selected' : '' ?>>Aprobada</option><option <?= $s['estado'] === 'Rechazada' ? 'selected' : '' ?>>Rechazada</option></select><button class="btn btn-primary btn-sm">Guardar</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="admin-section"><h2>Disponibilidad y bloqueos</h2><form method="post" class="disponibilidad-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="bloqueo"><div class="form-row"><div class="form-group"><label>Máquina</label><select name="maquina_id" class="form-control" required><?php foreach ($maquinas as $m): ?><option value="<?= $m['id'] ?>"><?= e($m['nombre']) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Desde</label><input type="date" name="fecha_inicio" class="form-control" required></div><div class="form-group"><label>Hasta</label><input type="date" name="fecha_fin" class="form-control" required></div></div><div class="form-group"><label>Motivo</label><input name="motivo" class="form-control" placeholder="Mantenimiento, evento..." maxlength="300"></div><button class="btn btn-primary">Bloquear fechas</button></form><div class="admin-table-wrap"><table class="tabla-extras admin-table"><thead><tr><th>Máquina</th><th>Intervalo</th><th>Motivo</th><th></th></tr></thead><tbody><?php foreach ($bloqueos as $b): ?><tr><td><?= e($b['maquina_nombre']) ?></td><td><?= e($b['fecha_inicio']) ?> → <?= e($b['fecha_fin']) ?></td><td><?= e($b['motivo']) ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="borrar_bloqueo"><input type="hidden" name="id" value="<?= $b['id'] ?>"><button class="btn btn-secondary btn-sm">Eliminar</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="admin-section"><div class="admin-section-header"><h2>Catálogo</h2><span class="admin-help">Los cambios se reflejan en la web pública al guardar.</span></div>
<form method="post" enctype="multipart/form-data" class="disponibilidad-form admin-new-machine"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="guardar_maquina"><input type="hidden" name="id" value="0"><h3>Añadir máquina</h3><div class="form-row"><div class="form-group"><label>Nombre</label><input name="nombre" class="form-control" required></div><div class="form-group"><label>Categoría</label><select name="categoria" class="form-control"><option>Grande</option><option>Pequeña</option></select></div><div class="form-group"><label>Precio/día (€)</label><input type="number" min="0" step="0.01" name="precio_base" class="form-control" required></div></div><div class="form-group"><label>Descripción</label><textarea name="descripcion" class="form-control" maxlength="1000"></textarea></div><div class="form-group"><label>Imagen</label><input type="file" name="imagen" accept=".jpg,.jpeg,.png,.webp" class="form-control"></div><button class="btn btn-primary">Añadir al catálogo</button></form>
<?php foreach ($maquinas as $m): ?><form method="post" enctype="multipart/form-data" class="disponibilidad-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="guardar_maquina"><input type="hidden" name="id" value="<?= $m['id'] ?>"><div class="admin-machine-title"><h3><?= e($m['nombre']) ?></h3><button class="btn btn-secondary btn-sm" type="submit" name="action" value="borrar_maquina" onclick="return confirm('¿Borrar esta máquina?')">Borrar</button></div><div class="form-row"><div class="form-group"><label>Nombre</label><input name="nombre" value="<?= e($m['nombre']) ?>" class="form-control" required></div><div class="form-group"><label>Categoría</label><select name="categoria" class="form-control"><option <?= $m['categoria'] === 'Grande' ? 'selected' : '' ?>>Grande</option><option <?= $m['categoria'] === 'Pequeña' ? 'selected' : '' ?>>Pequeña</option></select></div><div class="form-group"><label>Precio/día (€)</label><input type="number" min="0" step="0.01" name="precio_base" value="<?= e($m['precio_base']) ?>" class="form-control" required></div></div><div class="form-group"><label>Descripción</label><textarea name="descripcion" class="form-control" maxlength="1000"><?= e($m['descripcion']) ?></textarea></div><div class="form-group"><label>Cambiar imagen</label><input type="file" name="imagen" accept=".jpg,.jpeg,.png,.webp" class="form-control"></div><button class="btn btn-primary">Guardar cambios</button></form><?php endforeach; ?></section>
