<?php
declare(strict_types=1);
$done = false; $error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db = ['host'=>trim($_POST['db_host']??''),'port'=>(int)($_POST['db_port']??3306),'name'=>trim($_POST['db_name']??''),'user'=>trim($_POST['db_user']??''),'password'=>$_POST['db_password']??'','charset'=>'utf8mb4'];
    $adminUser=trim($_POST['admin_user']??'admin'); $adminPassword=$_POST['admin_password']??'';
    try { $pdo=new PDO(sprintf('mysql:host=db5021020332.hosting-data.io;port=3306;dbname=dbs15944211;charset=utf8mb4',$db['host'],$db['port'],$db['name']),$db['user'],$db['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $sql=file_get_contents(__DIR__.'/schema.sql'); $pdo->exec($sql); $count=(int)$pdo->query('SELECT COUNT(*) FROM maquinas')->fetchColumn(); if(!$count){$q=$pdo->prepare('INSERT INTO maquinas (nombre,descripcion,categoria,imagen_url,precio_base) VALUES (?,?,?,?,?)'); foreach([['Bartop Retro Clásico','Gabinete bartop de madera con más de 2000 juegos clásicos. Pantalla CRT de 21".','Grande','/img/placeholder.svg',180],['Bartop Pixel Art','Diseño artesanal con ilustraciones de píxel art pintadas a mano. 1500 juegos.','Grande','/img/placeholder.svg',200],['Mini Bartop Retro','Versión compacta ideal para mesas y espacios pequeños. 800 juegos.','Pequeña','/img/placeholder.svg',120],['Bartop Neon City','Gabinete con iluminación LED neon y temática cyberpunk.','Grande','/img/placeholder.svg',220],['Mini Bartop Madera Natural','Acabado en madera de haya vaporizada. Minimalista y elegante.','Pequeña','/img/placeholder.svg',130]] as $m)$q->execute($m);}$config="<?php\nreturn ".var_export(['db'=>$db,'admin'=>['user'=>$adminUser,'password_hash'=>password_hash($adminPassword,PASSWORD_DEFAULT)]],true).";\n"; if(!is_dir(__DIR__.'/app')||!is_writable(__DIR__.'/app'))throw new RuntimeException('La carpeta app no permite escritura temporal.'); file_put_contents(__DIR__.'/app/config.php',$config,LOCK_EX); $done=true; } catch(Throwable $e){$error='No se pudo completar la instalación: '.$e->getMessage();}
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instalación</title><link rel="stylesheet" href="/css/site.css"></head><body><main><div class="container"><div class="page-header"><h1>Instalación inicial</h1><p>Introduce estos datos directamente en IONOS. No los compartas por chat.</p></div><?php if($done): ?><div class="alert alert-success">Instalación completada. Elimina setup.php antes de abrir la web.</div><a class="btn btn-primary" href="/">Abrir web</a><?php else: ?><?php if($error): ?><div class="alert alert-error"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif; ?><form method="post" class="solicitud-form"><fieldset><legend>Base de datos</legend><?php foreach(['db_host'=>'Servidor','db_port'=>'Puerto','db_name'=>'Base de datos','db_user'=>'Usuario','db_password'=>'Contraseña'] as $name=>$label): ?><div class="form-group"><label><?=$label?></label><input class="form-control" name="<?=$name?>" type="<?=str_contains($name,'password')?'password':'text'?>" value="<?=htmlspecialchars($_POST[$name]??($name==='db_host'?'db5021020332.hosting-data.io':($name==='db_port'?'3306':($name==='db_name'?'dbs15944211':($name==='db_user'?'dbu4360934':'')))),ENT_QUOTES,'UTF-8')?>" required></div><?php endforeach; ?></fieldset><fieldset><legend>Administrador</legend><div class="form-group"><label>Usuario</label><input class="form-control" name="admin_user" value="admin" required></div><div class="form-group"><label>Contraseña</label><input class="form-control" name="admin_password" type="password" minlength="12" required></div></fieldset><button class="btn btn-primary">Instalar</button></form><?php endif; ?></div></main></body></html>
